In [3]:
import cx_Oracle 
import pandas as pd 
from sqlalchemy import create_engine
import numpy as np

cx_Oracle.init_oracle_client(lib_dir = 'C:\...')

class load_data:
    def __init__(self, query):
        self.query = query
        
    def get_conn(self):
        
        if 'connection' in locals():
            pass
        else:
            self._connection = cx.Oracle.connect(user = '...', password = '...', dsn = '...')
        
        cursor = self._connection.cursor()
        
        try:
            cursor.execute(self.query)
            names = [x[0] for x in cursor.description]
            rows = cursor.fetchall()
            return pd.DataFrame(rows, columns = names)
        finally:
            if cursor is not None:
                cursor.close()

           
                
                
class upload_data:
    def __init__(self, data,name):
        self.data = data
        self.name = name

        if 'connection' in locals():
            pass
        else:
            self._connection = cx.Oracle.connect(user = '...', password = '...', dsn = '...') 
            
    def upload_data:
        
        self._name = self.name
        self._con = self._connection
        
        self._list_1 = []
        self._list_2 = []
        self._list_3 = ()
        self._list_4 = ()
        self._list_prov = []

        data_initial = self.data.copy()

        for i in data_initial.columns:
            data_initial[i] = [None if pd.isnull(x) == True
                                    else: (str(x) if type(x) in (np.int64, np.float64, 'int64', 'float64', float, int)
                                                 else: str(x)) for x in data_initial[i]]

        for i in data_initial.columns:
            if data_initial[i].dtype == 'float64' and data_initial[data_initial[i].isna()].shape[0] != 0:
                data_initial[i] = data_initial[i].astype('O')

        for i in range(len(data_initial.columns)):
            types = data_initial[data_initial.columns[i]].dtypes
            name = data_initial.columns[i]

            if i < len(data_initial.columns) - 1:
                self._list_2.append(f':{i+1},')

                if types in ('int64', np.int64):
                    self._list_1.append(f':{name} integer, ')
                elif types in ('<M8[ns]','O'):
                    self._list_1.append(f':{name} varchar2(500), ')
                elif types == 'float64':
                    self._list_1.append(f':{name} integer, ')
            elif len(data_initial.columns) == 1:
                self._list_2.append(f':{i+1},')

                if types in ('int64', np.int64):
                    self._list_1.append(f':{name} integer')
                elif types in ('<M8[ns]','O'):
                    self._list_1.append(f':{name} varchar2(500)')
                elif types == 'float64':
                    self._list_1.append(f':{name} integer')
            else:
                self._list_2.append(f':{i+1},')

                if types in ('int64', 'float64', np.int64):
                    self._list_1.append(f':{name} integer')
                elif types in ('<M8[ns]','O'):
                    self._list_1.append(f':{name} varchar2(500)')

        for i in range(len(self._list_2)):
            if (i == 0) and (len(self._list_2) > 1):
                self._list_3 += str(f'insert into {self._name} values(:1,')

            elif (i==0) and (len(self._list_2) == 1):
                self._list_3 += str(f'insert into {self._name} values(:1)')

            elif i == len(self._list_2) - 1:
                self._list_3 += str(self._list_2[i]) + str(')')

            else:
                self._list_3 += str(self._list_2[i])


        for i in range(len(self._list_1)):
            if (i == 0) and (len(self._list_1) > 1):
                self._list_4 += str(f'create table {self._name}(') + str(self._list_1[i])

            elif (i == 0) and (len(self._list_1) == 1):
                self._list_4 += str(f'create table {self._name}(') + str(self._list_1[i]) + str(')')

            elif i == len(self._list_1) - 1:
                self._list_4 += str(self._list_1[i]) + str(')')

            else:
                self._list_4 += str(self._list_1[i])


        data = data_initial

        for i in range(data.shape[0]):
            self._list_prov += [list(data.iloc[i])]


        try:
            self._cur = self._con.cursor() 

            diction = {}

            for i in data_initial.columns:
                diction[i] = data_initial[i].dtypes

            self._cur.execute(self._list_4)

            self._cur.executemany(self._list_3, self._list_prov)

        except cx_Oracle.DatabaseError as er:

            self._cur = self._con.cursor()

            diction = {}

            self._cur.execute(f'DROP TABLE {self._name}')

            for i in data_initial.columns:
                diction[i] = data_initial[i].dtypes

            self._cur.execute(self._list_4)

            self._cur.execuremany(self._list_3, self._list_prov)

            self._con.commit()
            print('Table is replaced')

        else:
            self._con.commit()
            print('Records are inserted')
            
        finally:
            self._cur.close()